#ifndef _PINOUT_H
#define _PINOUT_H

#include <Arduino.h>

#define PIN_ENABLE_PWM_A 9
#define PIN_ENABLE_PWM_B 10

#define PIN_LED_FREQUENCY A0
#define PIN_LED_ENABLE A1
#define PIN_LED_DEBUG LED_BUILTIN

#define PIN_ENCODER_ENABLE_A 3
#define PIN_ENCODER_ENABLE_B 4
#define PIN_ENCODER_ENABLE_PRESS 5

#define PIN_ENCODER_FREQUENCY_A 8
#define PIN_ENCODER_FREQUENCY_B 2
#define PIN_ENCODER_FREQUENCY_PRESS 7

#define PIN_AD9833_FSYNC 6
#define PIN_AD9833_DATA 11
#define PIN_AD9833_CLOCK 13

#endif /* _PINOUT_H */
