#ifndef _PINOUT_H
#define _PINOUT_H

#include <Arduino.h>

#define PIN_ENABLE_PWM_A D9
#define PIN_ENABLE_PWM_B D10

#define PIN_LED_FREQUENCY A0
#define PIN_LED_ENABLE A1
#define PIN_LED_DEBUG LED_BUILTIN

#define PIN_ENCODER_ENABLE_A D3
#define PIN_ENCODER_ENABLE_B D4
#define PIN_ENCODER_ENABLE_PRESS D5

#define PIN_ENCODER_FREQUENCY_A D8
#define PIN_ENCODER_FREQUENCY_B D2
#define PIN_ENCODER_FREQUENCY_PRESS D7

#define PIN_AD9833_FSYNC D6
#define PIN_AD9833_DATA D11
#define PIN_AD9833_CLOCK D13

#endif /* _PINOUT_H */
